version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:

        filters:

          branches:

            only:
              - master

        requires:
          - build

jobs:
  docker:  
  - image: circleci/node:12.16.2

  steps:    
  - checkout    
  - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_muri_dev.sh”