# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:

        filters:

          branches:

            only:
              - master
              
        requires:
          -build
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:

      deploy-prod:

        docker:  
        
          # specify the version you desire here (you might not want node)  
          - image: circleci/node:12.16.2

          steps:    
            - checkout    
            - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_muri_dev.sh”