# V1 build2
version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP ./deploy_muri_dev.sh

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master